git:
  depth: 10
sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '6'
  - '7'
script:
  - npm run lint
  - npm test
after_success:
  - bash <(curl -s https://codecov.io/bash)
