version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout

      - restore_cache:
          name: Restore node_modules cache
          keys:
            - v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-node-{{ arch }}-{{ .Branch }}-
            - v1-node-{{ arch }}-

      - run: yarn install
      - run: yarn lint
      - run: yarn flow
      - run:
          command: |
            mkdir ~/junit
            yarn test --reporter xunit --reporter-options output=~/junit/test-results.xml
      - store_test_results:
          path: ~/junit
      - run: yarn build

      - save_cache:
          name: Save node_modules cache
          key: v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  deploy:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          name: Restore node_modules cache
          keys:
            - v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-node-{{ arch }}-{{ .Branch }}-
            - v1-node-{{ arch }}-

      - run: git config --global user.email "gh-pages@localhost"
      - run: git config --global user.name "npm gh-pages"
      - run: yarn install
      - run: yarn build
      - run: sh ./scripts/deploy.sh

      - save_cache:
          name: Save node_modules cache
          key: v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
